### ISSUE TITLE
Allow commenting out of lines in csv files

### ISSUE THREAD

**Issue by ramonawalls** [stuckyb/ontobuilder#27]
It would be a nice feature to be able to include an ontology in the imported_ontologies.csv file but be able to comment it out with a #. That way, I wouldn't have to retype the line for that ontology when I am playing around with including it or not.

**Comment by stuckyb** [comment]
Good suggestion, Ramona, and I just now implemented this feature.  However, rather than using a '#' to comment out a row in an input file, you add a column called "Ignore" and then put "yes" (or "y", "true", etc.) for any row you wish to "comment out".  Doing it this way, rather than with a '#', makes it portable across all input file types (CSV, spreadsheets).
